freelancehouseholdworkrecommender/urls.py
"""
freelancehouseholdworkrecommender URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib import messages

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib import messages
from users import views


app_name = "users"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    # Customer registration and login views
    path(
        "register/",
        views.CustomerRegistrationView.as_view(),
        name="customer_registration",
    ),
    path("activate/<uidb64>/<token>/", views.activate_account, name="activate_account"),
    path(
        "registration/done/",
        views.CustomerRegistrationDoneView.as_view(),
        name="registration_done",
    ),
    path("login/", views.CustomerLoginView.as_view(), name="customer_login"),
    path("logout/", views.CustomerLogoutView.as_view(), name="customer_logout"),
    path(
        "profile/", views.CustomerProfileUpdateView.as_view(), name="customer_profile"
    ),
    # Worker registration and login views
    path(
        "worker/register/",
        views.WorkerRegistrationView.as_view(),
        name="worker_registration",
    ),
    path("worker/login/", views.WorkerLoginView.as_view(), name="worker_login"),
    path("worker/logout/", views.WorkerLogoutView.as_view(), name="worker_logout"),
    path(
        "worker/profile/",
        views.WorkerProfileUpdateView.as_view(),
        name="worker_profile",
    ),
    # Password reset views
    path(
        "password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

# add the message tags for different levels
MESSAGE_TAGS = {
    messages.DEBUG: "debug",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models


class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_customer = models.BooleanField(default=False)
    is_worker = models.BooleanField(default=False)
    groups = models.ManyToManyField(Group, related_name="user+")
    user_permissions = models.ManyToManyField(Permission, related_name="user+")

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"


class Customer(User):
    phone_number = models.CharField(max_length=20, unique=True)
    location = models.CharField(max_length=100)
    email_verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        self.is_worker = False
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"


class Skill(models.Model):
    name = models.CharField(max_length=100)


class Worker(User):
    phone_number = models.CharField(max_length=20)
    location = models.CharField(max_length=100)
    skills = models.ManyToManyField(Skill)
    hourly_rate = models.FloatField()
    email_verified = models.BooleanField(default=False)
    is_available = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        self.is_customer = False
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Worker"
        verbose_name_plural = "Workers"

users/views.py
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.db.models import Avg
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DetailView,
    FormView,
    TemplateView,
    UpdateView,
)
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes
from .forms import (
    CustomerProfileUpdateForm,
    CustomerRegistrationForm,
    LoginForm,
    WorkerProfileUpdateForm,
    WorkerRegistrationForm,
)
from .models import Customer, Worker
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator

User = get_user_model()


class HomeView(TemplateView):
    template_name = "users/base.html"


class CustomerRegistrationView(CreateView):
    """
    A view for customer registration.

    On successful registration, sends email to customer and notification email to admin.

    """

    model = Customer
    form_class = CustomerRegistrationForm
    template_name = "users/registration_form.html"
    success_url = reverse_lazy("users:registration_done")

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("home")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """
        If form is valid, create a new customer and save to the database.

        If email, username, or phone number already exists, redirect back to registration form.

        """
        try:
            email = form.cleaned_data["email"]
            username = form.cleaned_data["username"]
            phone_number = form.cleaned_data["phone_number"]

            if User.objects.filter(email=email).exists():
                form.add_error("email", "Email already exists.")
                return self.form_invalid(form)

            if User.objects.filter(username=username).exists():
                form.add_error("username", "Username already exists.")
                return self.form_invalid(form)

            if Customer.objects.filter(phone_number=phone_number).exists():
                form.add_error("phone_number", "Phone number already exists.")
                return self.form_invalid(form)

            # Save customer to the database
            customer = form.save(commit=False)
            customer.is_customer = True
            customer.save()

            # Generate unique token for the customer
            uidb64 = urlsafe_base64_encode(force_bytes(customer.pk))
            token = default_token_generator.make_token(customer)

            # Construct the activation link
            activation_link = f"{self.request.scheme}://{self.request.get_host()}/users/activate/{uidb64}/{token}"

            # Send verification email to customer with activation link
            send_mail(
                subject="Verify your email",
                message=f"Please click the link below to verify your email: {activation_link}",
                from_email=settings.ADMIN_EMAIL,
                recipient_list=[customer.email],
                fail_silently=False,
            )

            # Send notification email to admin
            send_mail(
                subject="New customer registration",
                message="A new customer has registered on Freelance Household Work.",
                from_email=settings.ADMIN_EMAIL,
                recipient_list=[settings.ADMIN_EMAIL],
                fail_silently=False,
            )

            # Success message
            messages.success(
                self.request, "Your account has been created successfully!"
            )

            return super().form_valid(form)

        except Exception as e:
            form.add_error(None, str(e))
            return self.form_invalid(form)


class CustomerRegistrationDoneView(TemplateView):
    """
    A view to display a success message after customer registration is complete.
    """

    template_name = "users/registration_done.html"


def activate_account(request, uidb64, token):
    """
    Activate a customer account using the given uidb64 and token.

    If account is already active, redirect to login page with message.

    """
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        customer = get_object_or_404(Customer, pk=uid)
    except (TypeError, ValueError, OverflowError, Customer.DoesNotExist):
        customer = None

    if customer is not None and default_token_generator.check_token(customer, token):
        if not customer.email_verified:
            # activate the customer account
            customer.email_verified = True  # Set email_verified to True
            customer.save()
            messages.success(request, "Your account has been activated successfully!")
        else:
            messages.info(request, "Your account is already active.")
        return redirect("users:customer_login")
    else:
        messages.error(request, "Invalid activation link.")
        return redirect("users:base")


class CustomerLoginView(FormView):
    """
    A view for logging in a customer.

    Allows the customer to log in to their account.

    Parameters:
    - FormView (class): Django generic view for rendering a form.
    """

    template_name = "users/customer_login.html"
    form_class = LoginForm
    success_url = reverse_lazy("customer_profile")

    def form_valid(self, form):
        """
        Called when a valid form is submitted.

        Logs the user in and sends a message to confirm the action.

        Parameters:
        - form (LoginForm): The form that was submitted.

        Returns:
        - HttpResponse: A redirect to the success URL with a success message.
        """
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, email=email, password=password)

        if isinstance(user, Customer) and user.email_verified:
            login(self.request, user)
            messages.success(self.request, f"You are now logged in as {user.username}.")
            return super().form_valid(form)
        elif isinstance(user, Customer) and not user.email_verified:
            messages.error(
                self.request,
                "Your email address is not verified yet. Please check your email for a verification link.",
            )
            return redirect("users:customer_login")
        else:
            messages.error(self.request, "Invalid email or password.")
            return redirect("users:customer_login")

    def form_invalid(self, form):
        """
        Called when an invalid form is submitted.

        Sends an error message to the user.

        Parameters:
        - form (LoginForm): The form that was submitted.

        Returns:
        - HttpResponse: A redirect to the login URL with an error message.
        """

        messages.error(self.request, "Invalid email or password.")
        return redirect("users:customer_login")


@method_decorator(login_required(login_url="users:customer_login"), name="dispatch")
class CustomerLogoutView(LogoutView):
    """
    A view for logging out a customer.

    Allows the customer to log out of their account.

    Parameters:
    - LogoutView (class): Django generic view for logging a user out.
    """

    next_page = reverse_lazy("users:base")

    def dispatch(self, request, *args, **kwargs):
        """
        Dispatches the view.

        Logs the customer out and sends a message to confirm the action.

        Parameters:
        - request (HttpRequest): The HTTP request.
        - args: Additional arguments.
        - kwargs: Additional keyword arguments.

        Returns:
        - HttpResponse: A redirect to the next page URL with a success message.
        """
        messages.success(request, "You have been logged out.")
        return super().dispatch(request, *args, **kwargs)


@method_decorator(login_required(login_url="login"), name="dispatch")
class CustomerProfileUpdateView(UpdateView):
    """
    A view for updating a customer's profile.

    Allows the customer to update their profile details, such as their name, email,
    phone number, and location.

    Parameters:
    - UpdateView (class): Django generic view for updating objects in the database.
    """

    model = Customer
    form_class = CustomerProfileUpdateForm
    template_name = "users/customer_profile_update.html"
    success_url = reverse_lazy("customer_profile")

    def form_valid(self, form):
        """
        Called when a valid form is submitted.

        Saves the form and sends a message to the user to confirm the profile update.

        Parameters:
        - form (CustomerProfileUpdateForm): The form that was submitted.

        Returns:
        - HttpResponse: A redirect to the success URL with a success message.
        """
        response = super().form_valid(form)
        self.object.email_verified = False
        self.object.save()
        messages.success(self.request, "Profile updated successfully.")
        return response

    def get_object(self):
        """
        Gets the object being updated.

        Returns:
        - object (Customer): The customer object being updated.
        """
        return Customer.objects.get(user=self.request.user)


class WorkerRegistrationView(CreateView):
    """
    A view for worker registration.

users/templates/users/account_activation_sent.html
{% extends "users/base.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h2>Account activation email sent</h2>
      <p>
        We have sent an email to your email address. Please click the link in
        the email to activate your account.
      </p>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>{% include 'users/header.html' %}</header>
    <main class="mb-5">{% block content %}{% endblock %}</main>
    <footer>{% include 'users/footer.html' %}</footer>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

users/templates/users/customer_login.html
{% extends "users/base.html" %} {% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title text-center">Customer Login</h3>
        </div>
        <div class="card-body">
          {% if form.errors %}
          <div class="alert alert-danger">
            {% for field, errors in form.errors.items %}
            <strong>{{ field }}:</strong>
            {% for error in errors %} {{ error }}<br />
            {% endfor %} {% endfor %}
          </div>
          {% endif %}
          <form method="post">
  {% csrf_token %}
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <div class="form-group">
    <label for="{{ form.username.id_for_label }}">Email</label>
    {{ form.username }}
  </div>
  <div class="form-group">
    <label for="{{ form.password.id_for_label }}">Password</label>
    {{ form.password }}
  </div>
  <button type="submit" class="btn btn-primary btn-block mt-4">
    Login
  </button>
</form>

        </div>
        <div class="card-footer text-center">
          <a href="{% url 'users:password_reset' %}">Forgot password?</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/customer_profile.html
{% extends "users/base.html" %} {% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Profile</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ user.username }}</h6>
          <p class="card-text">{{ user.first_name }} {{ user.last_name }}</p>
          <p class="card-text">{{ user.email }}</p>
          <p class="card-text">{{ customer.phone_number }}</p>
          <p class="card-text">{{ customer.location }}</p>
          <a href="{% url 'customer_profile_update' %}" class="btn btn-primary"
            >Update Profile</a
          >
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/customer_profile_update.html
{% extends 'users/base.html' %} {% block content %}
<div class="container mt-5 mb-5">
  <h1 class="text-center">Update Profile</h1>
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.first_name.id_for_label }}">First name:</label>
          {{ form.first_name }} {% if form.first_name.errors %}
          <div class="text-danger">
            {% for error in form.first_name.errors %} {{ error }} {% endfor %}
          </div>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.last_name.id_for_label }}">Last name:</label>
          {{ form.last_name }} {% if form.last_name.errors %}
          <div class="text-danger">
            {% for error in form.last_name.errors %} {{ error }} {% endfor %}
          </div>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.email.id_for_label }}">Email:</label>
          {{ form.email }} {% if form.email.errors %}
          <div class="text-danger">
            {% for error in form.email.errors %} {{ error }} {% endfor %}
          </div>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.phone_number.id_for_label }}"
            >Phone number:</label
          >
          {{ form.phone_number }} {% if form.phone_number.errors %}
          <div class="text-danger">
            {% for error in form.phone_number.errors %} {{ error }} {% endfor
            %}
          </div>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.location.id_for_label }}">Location:</label>
          {{ form.location }} {% if form.location.errors %}
          <div class="text-danger">
            {% for error in form.location.errors %} {{ error }} {% endfor %}
          </div>
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/footer.html
<footer class="bg-light text-center text-lg-start">
  <div class="container p-4">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Contact Us</h5>

        <p>
          If you have any questions or suggestions, please don't hesitate to
          get in touch with us.
        </p>

        <ul class="list-unstyled mb-0">
          <li>
            <i class="fas fa-map-marker-alt fa-2x"></i>
            <p>Bijayachowk, Gaushala</p>
          </li>

          <li>
            <i class="fas fa-phone mt-4 fa-2x"></i>
            <p>+977-123456789</p>
          </li>

          <li>
            <i class="fas fa-envelope mt-4 fa-2x"></i>
            <p>info@fhhwr.com</p>
          </li>
        </ul>
      </div>

      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-dark">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-dark">Link 4</a>
          </li>
        </ul>
      </div>

      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Social Media</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-dark"
              ><i class="fab fa-facebook-f fa-2x"></i
            ></a>
          </li>
          <li>
            <a href="#!" class="text-dark"
              ><i class="fab fa-twitter fa-2x"></i
            ></a>
          </li>
          <li>
            <a href="#!" class="text-dark"
              ><i class="fab fa-linkedin-in fa-2x"></i
            ></a>
          </li>
          <li>
            <a href="#!" class="text-dark"
              ><i class="fab fa-instagram fa-2x"></i
            ></a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2023 Freelance Household Work Recommender | All Rights Reserved
  </div>
</footer>

users/templates/users/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>Freelance Household Work Recommender</title>
    <!-- <link rel="stylesheet" href="base.css" /> -->
  </head>

  <body>
    <!-- navbar start -->
    <nav
      class="navbar navbar-expand-lg bg-body-tertiary"
      style="background-color: #e3f2fd"
    >
      <a class="navbar-brand" href="">FreelanceHHWR</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse ml-5" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href=""
              >Home <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="faq.html">faq</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:customer_logout' %}"
              >Logout</a
            >
          </li>
          {% else %}
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
              >Login</a
            >
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'users:customer_login' %}"
                >Customer</a
              >
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'users:worker_login' %}"
                >Worker</a
              >
            </div>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
              >Register</a
            >
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a
                class="dropdown-item"
                href="{% url 'users:customer_registration' %}"
                >Customer</a
              >
              <div class="dropdown-divider"></div>
              <a
                class="dropdown-item"
                href="{% url 'users:worker_registration' %}"
                >Worker</a
              >
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </body>
</html>

users/templates/users/registration_done.html
{% extends "users/base.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h2>Account activation email sent</h2>
      <p>
        We have sent an email to your email address. Please click the link in
        the email to activate your account.
      </p>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/worker_profile.html
{% extends "users/base.html" %} {% block content %}
<h1>Worker Profile</h1>
<p>Name: {{ worker.user.get_full_name }}</p>
<p>Email: {{ worker.user.email }}</p>
<p>Phone number: {{ worker.phone_number }}</p>
<p>Location: {{ worker.location }}</p>
<p>Hourly rate: {{ worker.hourly_rate }}</p>
<p>Skills:</p>
<ul>
  {% for skill in worker.skills.all %}
  <li>{{ skill.name }}</li>
  {% empty %}
  <li>No skills added yet.</li>
  {% endfor %}
</ul>
{% endblock %}

users/templates/users/worker_profile_update.html
{% extends "users/base.html" %} {% block content %} worker profile update {%
endblock %}

users/templates/users/worker_registration_form.html
{% extends "users/base.html" %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h2>Worker Registration</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.email.id_for_label }}">Email address:</label>
          {{ form.email }} {% if form.email.errors %}
          <ul class="errorlist">
            {% for error in form.email.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.username.id_for_label }}">Username:</label>
          {{ form.username }} {% if form.username.errors %}
          <ul class="errorlist">
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.password1.id_for_label }}">Password:</label>
          {{ form.password1 }} {% if form.password1.errors %}
          <ul class="errorlist">
            {% for error in form.password1.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.password2.id_for_label }}"
            >Confirm password:</label
          >
          {{ form.password2 }} {% if form.password2.errors %}
          <ul class="errorlist">
            {% for error in form.password2.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.phone_number.id_for_label }}"
            >Phone number:</label
          >
          {{ form.phone_number }} {% if form.phone_number.errors %}
          <ul class="errorlist">
            {% for error in form.phone_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.location.id_for_label }}">Location:</label>
          {{ form.location }} {% if form.location.errors %}
          <ul class="errorlist">
            {% for error in form.location.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.skills.id_for_label }}">Skills:</label>
          {{ form.skills }} {% if form.skills.errors %}
          <ul class="errorlist">
            {% for error in form.skills.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="{{ form.hourly_rate.id_for_label }}">Hourly rate:</label>
          {{ form.hourly_rate }} {% if form.hourly_rate.errors %}
          <ul class="errorlist">
            {% for error in form.hourly_rate.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <div class="mt-3">
        Already have an account?
        <a href="{% url 'users:worker_login' %}">Login here</a>.
      </div>
    </div>
  </div>
</div>

{% endblock %}